/*
 * CAPIF_API_Invoker_Management_API
 *
 * API for API invoker management. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Information about the API Invoker that requested to onboard
type ApiInvokerEnrolmentDetails struct {
	// API invoker ID assigned by the CAPIF core function to the API invoker while on-boarding the API invoker. Shall not be present in the HTTP POST request from the API invoker to the CAPIF core function, to on-board itself. Shall be present in all other HTTP requests and responses.
	ApiInvokerId string `json:"apiInvokerId,omitempty"`

	OnboardingInformation *OnboardingInformation `json:"onboardingInformation"`

	NotificationDestination *Ts29122CommonDataYamlcomponentsschemasUri `json:"notificationDestination"`
	// Set to true by Subscriber to request the CAPIF core function to send a test notification as defined in in subclause 7.6. Set to false or omitted otherwise.
	RequestTestNotification bool `json:"requestTestNotification,omitempty"`

	WebsockNotifConfig *Ts29122CommonDataYamlcomponentsschemasWebsockNotifConfig `json:"websockNotifConfig,omitempty"`

	ApiList *ApiList `json:"apiList,omitempty"`
	// Generic information related to the API invoker such as details of the device or the application.
	ApiInvokerInformation string `json:"apiInvokerInformation,omitempty"`

	SupportedFeatures *Ts29571CommonDataYamlcomponentsschemasSupportedFeatures `json:"supportedFeatures,omitempty"`
}
