/*
 * CAPIF_API_Invoker_Management_API
 *
 * API for API invoker management. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OnboardingNotification struct {
	// Set to \"true\" indicate successful on-boarding. Otherwise set to \"false\"
	Result bool `json:"result"`

	ResourceLocation *Ts29122CommonDataYamlcomponentsschemasUri `json:"resourceLocation,omitempty"`

	ApiInvokerEnrolmentDetails *ApiInvokerEnrolmentDetails `json:"apiInvokerEnrolmentDetails,omitempty"`

	ApiList *ApiList `json:"apiList,omitempty"`
}
