/*
 * CAPIF_API_Invoker_Management_API
 *
 * API for API invoker management. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a list of APIs.
type ApiList struct {
	// The list of service APIs that the API Invoker is allowed to invoke.
	ServiceAPIDescriptions []Ts29222CapifPublishServiceApiYamlcomponentsschemasServiceApiDescription `json:"serviceAPIDescriptions,omitempty"`
}
